// Synthetic room-photo fixtures, generated at test time.
//
// No real photographs and no real location data live in the repository: every
// image here is a flat colour generated by sharp, and the "GPS" is an invented
// latitude reference written only to prove it is stripped.

import sharp from 'sharp'
import zlib from 'node:zlib'

const colour = { r: 176, g: 140, b: 96 }

export const blank = (width, height, { alpha = false } = {}) => sharp({
  create: {
    width,
    height,
    channels: alpha ? 4 : 3,
    background: alpha ? { ...colour, alpha: 0.5 } : colour,
  },
})

export const jpeg = (width = 1600, height = 1200) => blank(width, height).jpeg({ quality: 90 }).toBuffer()
export const png = (width = 1200, height = 900, options) => blank(width, height, options).png().toBuffer()
export const webp = (width = 1200, height = 900) => blank(width, height).webp().toBuffer()
export const gif = (width = 800, height = 800) => blank(width, height).gif().toBuffer()
export const tiff = (width = 800, height = 800) => blank(width, height).tiff().toBuffer()

/** A JPEG carrying EXIF (including a GPS IFD), XMP and a Display P3 ICC profile. */
export const jpegWithPrivateMetadata = (width = 1600, height = 1200) => blank(width, height)
  .withExif({
    IFD0: { Artist: 'Fixture Author', Copyright: 'Fixture' },
    IFD3: { GPSLatitudeRef: 'N', GPSLongitudeRef: 'E' },
  })
  .withXmp('<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" dc:creator="Fixture Author"/></rdf:RDF></x:xmpmeta>')
  .withIccProfile('p3')
  .jpeg({ quality: 90 })
  .toBuffer()

/** Stored landscape pixels with EXIF Orientation 6 ("rotate 90° clockwise to view"). */
export const jpegWithOrientation6 = (storedWidth = 1200, storedHeight = 800) => blank(storedWidth, storedHeight)
  .withMetadata({ orientation: 6 })
  .jpeg()
  .toBuffer()

/** The EXIF tag that points at the GPS IFD (0x8825), little-endian as libvips writes it. */
export const GPS_IFD_POINTER_TAG = Buffer.from([0x25, 0x88])

/** Half of a real JPEG: valid signature and header, missing pixel data. */
export const truncatedJpeg = async () => {
  const full = await blank(1600, 1200).jpeg({ quality: 95 }).toBuffer()
  return full.subarray(0, Math.floor(full.length / 2))
}

const pngChunk = (type, data) => {
  const length = Buffer.alloc(4)
  length.writeUInt32BE(data.length)
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data])
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(zlib.crc32(body))
  return Buffer.concat([length, body, crc])
}

/**
 * A few hundred bytes whose PNG header claims `width` × `height` pixels — a
 * decompression bomb's shape, without the memory cost of a real one.
 */
export const pngClaimingDimensions = (width, height) => {
  const header = Buffer.alloc(13)
  header.writeUInt32BE(width, 0)
  header.writeUInt32BE(height, 4)
  header[8] = 8 // bit depth
  header[9] = 2 // truecolour
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', header),
    pngChunk('IDAT', zlib.deflateSync(Buffer.alloc(64))),
    pngChunk('IEND', Buffer.alloc(0)),
  ])
}

export const svg = () => Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="2000" height="1500"><rect width="2000" height="1500"/></svg>')

export const textFile = () => Buffer.from('This is a plain text file pretending to be a photo of a living room.\n')

/** The ISO-BMFF signature an iPhone HEIC starts with (not a decodable image). */
export const heicSignature = () => Buffer.concat([
  Buffer.from([0x00, 0x00, 0x00, 0x18]),
  Buffer.from('ftypheic', 'ascii'),
  Buffer.alloc(64),
])
