const keys = ['title', 'free', 'square', 'landscape', 'portrait', 'wide', 'tall', 'reset', 'zoomOut', 'zoomIn', 'zoom', 'hint', 'cancel', 'apply', 'applying', 'error', 'edit', 'remove']
const values = {
  en: ['Crop image', 'Free', 'Square', 'Landscape', 'Portrait', 'Wide', 'Tall', 'Reset', 'Zoom out', 'Zoom in', 'Zoom level', 'Drag edges to resize and drag inside to move. Pinch or Ctrl+scroll to zoom; scroll to pan.', 'Cancel', 'Apply Crop', 'Applying…', 'Unable to crop this image. Try uploading the original file again.', 'Crop image', 'Remove crop'],
  tr: ['Görseli kırp', 'Serbest', 'Kare', 'Yatay', 'Dikey', 'Geniş', 'Uzun', 'Sıfırla', 'Uzaklaştır', 'Yakınlaştır', 'Yakınlaştırma düzeyi', 'Boyut için kenarları, taşımak için içini sürükleyin. Yakınlaştırmak için iki parmak veya Ctrl+kaydırma kullanın; gezinmek için kaydırın.', 'İptal', 'Kırpmayı uygula', 'Uygulanıyor…', 'Bu görsel kırpılamadı. Orijinal dosyayı yeniden yüklemeyi deneyin.', 'Görseli kırp', 'Kırpmayı kaldır'],
  ar: ['قص الصورة', 'حر', 'مربع', 'أفقي', 'عمودي', 'عريض', 'طويل', 'إعادة ضبط', 'تصغير', 'تكبير', 'مستوى التكبير', 'اسحب الحواف لتغيير الحجم والداخل للتحريك. استخدم إصبعين أو Ctrl مع التمرير للتكبير، والتمرير للتنقل.', 'إلغاء', 'تطبيق القص', 'جارٍ التطبيق…', 'تعذر قص الصورة. حاول رفع الملف الأصلي مجددًا.', 'قص الصورة', 'إزالة القص'],
  de: ['Bild zuschneiden', 'Frei', 'Quadrat', 'Querformat', 'Hochformat', 'Breit', 'Schmal', 'Zurücksetzen', 'Verkleinern', 'Vergrößern', 'Zoomstufe', 'Ränder zum Skalieren und innen zum Verschieben ziehen. Mit zwei Fingern oder Strg+Scrollen zoomen; zum Schwenken scrollen.', 'Abbrechen', 'Zuschnitt anwenden', 'Wird angewendet…', 'Dieses Bild konnte nicht zugeschnitten werden. Laden Sie die Originaldatei erneut hoch.', 'Bild zuschneiden', 'Zuschnitt entfernen'],
  ru: ['Обрезать изображение', 'Свободно', 'Квадрат', 'Альбом', 'Портрет', 'Широкий', 'Высокий', 'Сбросить', 'Уменьшить', 'Увеличить', 'Масштаб', 'Тяните края для изменения размера, середину — для перемещения. Масштабируйте двумя пальцами или Ctrl+прокруткой; прокручивайте для перемещения.', 'Отмена', 'Применить обрезку', 'Применение…', 'Не удалось обрезать изображение. Попробуйте загрузить исходный файл снова.', 'Обрезать изображение', 'Удалить обрезку'],
  ur: ['تصویر تراشیں', 'آزاد', 'مربع', 'افقی', 'عمودی', 'چوڑا', 'لمبا', 'دوبارہ ترتیب دیں', 'زوم کم کریں', 'زوم بڑھائیں', 'زوم کی سطح', 'سائز بدلنے کے لیے کنارے اور منتقل کرنے کے لیے اندر کا حصہ کھینچیں۔ زوم کے لیے دو انگلیاں یا Ctrl کے ساتھ اسکرول کریں؛ حرکت کے لیے اسکرول کریں۔', 'منسوخ', 'کراپ لاگو کریں', 'لاگو ہو رہا ہے…', 'تصویر تراشی نہیں جا سکی۔ اصل فائل دوبارہ اپ لوڈ کریں۔', 'تصویر تراشیں', 'کراپ ہٹائیں'],
}
export const imageCropLabels = language => Object.fromEntries(keys.map((key, i) => [key, (values[language] || values.en)[i]]))
