const keys = ['heading', 'addSection', 'section', 'label', 'title', 'description', 'conclusion', 'addImage', 'imageTitle', 'imageDescription', 'remove', 'up', 'down', 'documents', 'addDocument', 'fileName', 'fileType', 'url', 'upload', 'failed', 'invalidFile', 'closeImage', 'legacy', 'image', 'limits']
const translations = {
  en: ['Their Work', 'Add section', 'Section', 'Eyebrow label', 'Title', 'Description', 'Conclusion', 'Add image', 'Image title', 'Image description', 'Remove', 'Move up', 'Move down', 'Documents', 'Add document', 'File name', 'File type', 'URL', 'Upload', 'Upload failed. Please try again.', 'Choose a PDF, Word or PowerPoint file, up to 20 MB.', 'Close image', 'Existing gallery', 'Image', 'Up to 12 sections, 24 images per section (120 total), and 12 documents.'],
  tr: ['Çalışmaları', 'Bölüm ekle', 'Bölüm', 'Üst etiket', 'Başlık', 'Açıklama', 'Sonuç', 'Görsel ekle', 'Görsel başlığı', 'Görsel açıklaması', 'Kaldır', 'Yukarı taşı', 'Aşağı taşı', 'Belgeler', 'Belge ekle', 'Dosya adı', 'Dosya türü', 'URL', 'Yükle', 'Yükleme başarısız. Lütfen tekrar deneyin.', 'En fazla 20 MB boyutunda PDF, Word veya PowerPoint dosyası seçin.', 'Görseli kapat', 'Mevcut galeri', 'Görsel', 'En fazla 12 bölüm, bölüm başına 24 görsel (toplam 120) ve 12 belge.'],
  ar: ['أعمالهم', 'إضافة قسم', 'القسم', 'وسم علوي', 'العنوان', 'الوصف', 'الخاتمة', 'إضافة صورة', 'عنوان الصورة', 'وصف الصورة', 'إزالة', 'نقل لأعلى', 'نقل لأسفل', 'المستندات', 'إضافة مستند', 'اسم الملف', 'نوع الملف', 'الرابط', 'رفع', 'فشل الرفع. يرجى المحاولة مجددًا.', 'اختر ملف PDF أو Word أو PowerPoint بحجم لا يتجاوز 20 ميغابايت.', 'إغلاق الصورة', 'المعرض الحالي', 'صورة', 'حتى 12 قسمًا و24 صورة لكل قسم (120 إجمالًا) و12 مستندًا.'],
  de: ['Ihre Arbeit', 'Abschnitt hinzufügen', 'Abschnitt', 'Oberzeile', 'Titel', 'Beschreibung', 'Fazit', 'Bild hinzufügen', 'Bildtitel', 'Bildbeschreibung', 'Entfernen', 'Nach oben', 'Nach unten', 'Dokumente', 'Dokument hinzufügen', 'Dateiname', 'Dateityp', 'URL', 'Hochladen', 'Upload fehlgeschlagen. Bitte erneut versuchen.', 'Wählen Sie eine PDF-, Word- oder PowerPoint-Datei bis 20 MB.', 'Bild schließen', 'Vorhandene Galerie', 'Bild', 'Bis zu 12 Abschnitte, 24 Bilder pro Abschnitt (120 insgesamt) und 12 Dokumente.'],
  ru: ['Их работы', 'Добавить раздел', 'Раздел', 'Надзаголовок', 'Заголовок', 'Описание', 'Заключение', 'Добавить изображение', 'Название изображения', 'Описание изображения', 'Удалить', 'Переместить вверх', 'Переместить вниз', 'Документы', 'Добавить документ', 'Имя файла', 'Тип файла', 'Ссылка', 'Загрузить', 'Загрузка не удалась. Повторите попытку.', 'Выберите файл PDF, Word или PowerPoint размером до 20 МБ.', 'Закрыть изображение', 'Существующая галерея', 'Изображение', 'До 12 разделов, 24 изображений в каждом (120 всего) и 12 документов.'],
  ur: ['ان کے کام', 'سیکشن شامل کریں', 'سیکشن', 'بالائی لیبل', 'عنوان', 'تفصیل', 'اختتام', 'تصویر شامل کریں', 'تصویر کا عنوان', 'تصویر کی تفصیل', 'ہٹائیں', 'اوپر منتقل کریں', 'نیچے منتقل کریں', 'دستاویزات', 'دستاویز شامل کریں', 'فائل کا نام', 'فائل کی قسم', 'لنک', 'اپ لوڈ کریں', 'اپ لوڈ ناکام ہوا۔ دوبارہ کوشش کریں۔', '20 ایم بی تک کی PDF، Word یا PowerPoint فائل منتخب کریں۔', 'تصویر بند کریں', 'موجودہ گیلری', 'تصویر', 'زیادہ سے زیادہ 12 سیکشن، ہر سیکشن میں 24 تصاویر (کل 120) اور 12 دستاویزات۔'],
}
export const teamWorkLabels = language => Object.fromEntries(keys.map((key, i) => [key, (translations[language] || translations.en)[i]]))
