import translations from '../locales/translations.js'

/*
 * PAGE CONTENT ↔ CATALOGUE — where each CMS text field's built-in wording lives.
 *
 * A public page reads a field as `cms('heroLabel', t.hero.label)`: the stored
 * value for the visitor's language if there is one, otherwise the catalogue
 * translation named in the second argument. That second argument is written
 * in each page component, so nothing else could know what a visitor falls back
 * to. This table states it once, as a path into translations.js:
 *
 *   home.heroLabel            → 'hero.label'
 *   architecture.service1Title → 'architecturePage.services.0.title'
 *
 * It exists for the Page Content editor, which shows the admin what visitors
 * of each language currently see. It changes nothing about how a page renders.
 *
 * It must stay in step with the pages. tests/pageContentTranslationStatus.test.js
 * re-reads every page's cms() calls and fails if a path here disagrees, or if a
 * registry text field has no entry.
 */
export const PAGE_CONTENT_CATALOGUE_PATHS = {
  home: {
    heroLabel: 'hero.label',
    heroHeading1: 'hero.heading1',
    heroHeading2: 'hero.heading2',
    heroHeading3: 'hero.heading3',
    heroCtaPrimary: 'hero.ctaPrimary',
    heroCtaSecondary: 'hero.ctaSecondary',
    servicesLabel: 'services.label',
    servicesHeading: 'services.heading',
    servicesSubheading: 'services.subheading',
    aboutLabel: 'about.label',
    aboutHeading: 'about.heading',
    aboutBody1: 'about.body1',
    aboutBody2: 'about.body2',
    aboutCta: 'about.cta',
    browseLabel: 'browse.label',
    browseHeading: 'browse.heading',
    browseListings: 'browse.listings',
    browseSaleTitle: 'browse.sale.title',
    browseSaleDesc: 'browse.sale.desc',
    browseSaleBtn: 'browse.sale.btn',
    browseRentTitle: 'browse.rent.title',
    browseRentDesc: 'browse.rent.desc',
    browseRentBtn: 'browse.rent.btn',
    trustLabel: 'trust.label',
    trustHeading: 'trust.heading',
    trustBody: 'trust.body',
    processLabel: 'process.label',
    processHeading: 'process.heading',
    featuredLabel: 'featured.label',
    featuredHeading: 'featured.heading',
    featuredSubtitle: 'featured.subtitle',
    featuredViewAll: 'featured.viewAll',
    projectsLabel: 'projects.label',
    projectsHeading: 'projects.heading',
    projectsSubtitle: 'projects.subtitle',
    projectsViewAll: 'projects.viewAll',
    statsLabel1: 'stats.properties',
    statsLabel2: 'stats.years',
    statsLabel3: 'stats.clients',
    statsLabel4: 'stats.districts',
    testimonialsLabel: 'testimonials.label',
    testimonialsHeading: 'testimonials.heading',
    partnersLabel: 'partners.label',
    ctaHeading: 'cta.heading',
    ctaBody: 'cta.body',
    ctaBrowse: 'cta.browse',
    ctaContact: 'cta.contact',
  },
  architecture: {
    heroLabel: 'architecturePage.label',
    heroHeading: 'architecturePage.h1',
    heroSubtitle: 'architecturePage.subtitle',
    heroCtaPrimary: 'architecturePage.ctaPrimary',
    heroCtaSecondary: 'architecturePage.ctaSecondary',
    showroomLabel: 'architecturePage.showroomLabel',
    showroomHeading: 'architecturePage.showroomHeading',
    servicesLabel: 'architecturePage.servicesLabel',
    servicesHeading: 'architecturePage.servicesHeading',
    service1Title: 'architecturePage.services.0.title',
    service1Desc: 'architecturePage.services.0.desc',
    service2Title: 'architecturePage.services.1.title',
    service2Desc: 'architecturePage.services.1.desc',
    service3Title: 'architecturePage.services.2.title',
    service3Desc: 'architecturePage.services.2.desc',
    service4Title: 'architecturePage.services.3.title',
    service4Desc: 'architecturePage.services.3.desc',
    processLabel: 'architecturePage.processLabel',
    processHeading: 'architecturePage.processHeading',
    processStep1: 'architecturePage.processSteps.0',
    processStep2: 'architecturePage.processSteps.1',
    processStep3: 'architecturePage.processSteps.2',
    processStep4: 'architecturePage.processSteps.3',
    ctaHeading: 'architecturePage.ctaHeading',
    ctaBody: 'architecturePage.ctaBody',
    ctaBtn: 'architecturePage.ctaBtn',
  },
  construction: {
    heroLabel: 'constructionPage.label',
    heroHeading: 'constructionPage.h1',
    heroSubtitle: 'constructionPage.subtitle',
    heroCtaPrimary: 'constructionPage.ctaPrimary',
    heroCtaSecondary: 'constructionPage.ctaSecondary',
    viewerLabel: 'constructionPage.viewerLabel',
    viewerHeading: 'constructionPage.viewerHeading',
    viewerDesc: 'constructionPage.viewerDesc',
    progressLabel: 'constructionPage.progressLabel',
    completionLabel: 'constructionPage.completionLabel',
    servicesLabel: 'constructionPage.servicesLabel',
    servicesHeading: 'constructionPage.servicesHeading',
    processLabel: 'constructionPage.processLabel',
    processHeading: 'constructionPage.processHeading',
    seismicLabel: 'constructionPage.seismicLabel',
    seismicHeading: 'constructionPage.seismicHeading',
    seismicBody: 'constructionPage.seismicBody',
    showroomLabel: 'constructionPage.showroomLabel',
    showroomHeading: 'constructionPage.showroomHeading',
    ctaHeading: 'constructionPage.ctaHeading',
    ctaBody: 'constructionPage.ctaBody',
    ctaBtn: 'constructionPage.ctaBtn',
  },
  renovation: {
    heroLabel: 'renovationPage.label',
    heroHeading: 'renovationPage.h1',
    heroSubtitle: 'renovationPage.subtitle',
    heroCtaPrimary: 'renovationPage.ctaPrimary',
    heroCtaSecondary: 'renovationPage.ctaSecondary',
    transformLabel: 'renovationPage.transformLabel',
    transformHeading: 'renovationPage.transformHeading',
    beforeTitle: 'renovationPage.before',
    afterTitle: 'renovationPage.after',
    beforeItem1: 'renovationPage.beforeItems.0',
    beforeItem2: 'renovationPage.beforeItems.1',
    beforeItem3: 'renovationPage.beforeItems.2',
    beforeItem4: 'renovationPage.beforeItems.3',
    afterItem1: 'renovationPage.afterItems.0',
    afterItem2: 'renovationPage.afterItems.1',
    afterItem3: 'renovationPage.afterItems.2',
    afterItem4: 'renovationPage.afterItems.3',
    studioLabel: 'renovationPage.studioLabel',
    studioHeading: 'renovationPage.studioHeading',
    studioDesc: 'renovationPage.studioDesc',
    paletteLabel: 'renovationPage.paletteLabel',
    paletteHeading: 'renovationPage.paletteHeading',
    servicesLabel: 'renovationPage.servicesLabel',
    servicesHeading: 'renovationPage.servicesHeading',
    service1Title: 'renovationPage.services.0.title',
    service1Desc: 'renovationPage.services.0.desc',
    service2Title: 'renovationPage.services.1.title',
    service2Desc: 'renovationPage.services.1.desc',
    service3Title: 'renovationPage.services.2.title',
    service3Desc: 'renovationPage.services.2.desc',
    service4Title: 'renovationPage.services.3.title',
    service4Desc: 'renovationPage.services.3.desc',
    showroomLabel: 'renovationPage.showroomLabel',
    showroomHeading: 'renovationPage.showroomHeading',
    ctaHeading: 'renovationPage.ctaHeading',
    ctaBody: 'renovationPage.ctaBody',
    ctaBtn: 'renovationPage.ctaBtn',
  },
  "interior-design": {
    heroLabel: 'interiorPage.label',
    heroHeading: 'interiorPage.h1',
    heroSubtitle: 'interiorPage.subtitle',
    heroCtaPrimary: 'interiorPage.ctaPrimary',
    heroCtaSecondary: 'interiorPage.ctaSecondary',
    stylesLabel: 'interiorPage.stylesLabel',
    stylesHeading: 'interiorPage.stylesHeading',
    stylesFilterHint: 'interiorPage.stylesFilterHint',
    showroomLabel: 'interiorPage.showroomLabel',
    showroomHeading: 'interiorPage.showroomHeading',
    finishesLabel: 'interiorPage.finishesLabel',
    finishesHeading: 'interiorPage.finishesHeading',
    previewLabel: 'interiorPage.previewLabel',
    paletteHeading: 'interiorPage.paletteHeading',
    servicesLabel: 'interiorPage.servicesLabel',
    servicesHeading: 'interiorPage.servicesHeading',
    service1Title: 'interiorPage.services.0.title',
    service1Desc: 'interiorPage.services.0.desc',
    service2Title: 'interiorPage.services.1.title',
    service2Desc: 'interiorPage.services.1.desc',
    service3Title: 'interiorPage.services.2.title',
    service3Desc: 'interiorPage.services.2.desc',
    service4Title: 'interiorPage.services.3.title',
    service4Desc: 'interiorPage.services.3.desc',
    ctaHeading: 'interiorPage.ctaHeading',
    ctaBody: 'interiorPage.ctaBody',
    ctaBtn: 'interiorPage.ctaBtn',
  },
  team: {
    heroLabel: 'teamPage.label',
    heroHeading: 'teamPage.heading',
    heroSubtitle: 'teamPage.subtitle',
    emptyText: 'teamPage.empty',
  },
  contact: {
    heroLabel: 'contactPage.label',
    heroHeading: 'contactPage.heading',
    heroSubtitle: 'contactPage.subtitle',
    officeLocationLabel: 'contactPage.officeLocation',
    interestLabel: 'contactPage.interestLabel',
    sendBtn: 'contactPage.sendBtn',
    successHeading: 'contactPage.successHeading',
    successBody: 'contactPage.successBody',
  },
}

/**
 * The built-in text for a field in a language, or '' when the catalogue has
 * none. Never throws: an unknown page, field or language is simply ''.
 */
export const catalogueText = (pageKey, fieldKey, language) => {
  const path = PAGE_CONTENT_CATALOGUE_PATHS[pageKey]?.[fieldKey]
  if (!path) return ''
  const value = path.split('.').reduce((node, key) => (node == null ? node : node[key]), translations[language])
  return typeof value === 'string' ? value : ''
}
